# 4.1 Tensor

## 4.1.1 Scalar
- 흔히 아는 상숫값
    - 하나의 값을 표현할 때 1개의 수치로 표현

In [1]:
import torch

scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [8]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


### 사칙연산: +, -, *, /

In [3]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [5]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [6]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [7]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


### 사칙연산: .add, .sub, .mul, .div

In [9]:
torch.add(scalar1, scalar2)

tensor([4.])

In [10]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [11]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [13]:
torch.div(scalar1, scalar2)

tensor([0.3333])

## 4.1.2 Vector

- 2개 이상의 수치를 하나의 값으로 표현

In [14]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [16]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


### 사칙연산: +, -, *, /

In [17]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [18]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [19]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [20]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


### 사칙연산: .add, .sub, .mul, .div

In [21]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [22]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [23]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [25]:
torch.div(vector1, vector2)
# 1 2 3
# 4 5 6

tensor([0.2500, 0.4000, 0.5000])

## 4.1.3 Matrix 

In [26]:
matrix1 = torch.tensor([[1., 2.],
                        [3., 4,]
                       ])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
matrix2 = torch.tensor([[5., 6.],
                        [7., 8,]
                       ])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


### 사칙연산: +, -, *, /

In [29]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [30]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [32]:
# element-wise multiplication
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [33]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


### 사칙연산: .add, .sub, .mul, .div

In [34]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [35]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [36]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [37]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

### 내적: .matmul

In [44]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

## 4.1.4 tensor

- 행렬: 2차원 배열
- 텐서: 2차원 이상의 배열

In [38]:
tensor1 = torch.tensor([
    [[1., 2.], [3., 4,]],
    [[5., 6.], [7., 8.]]
])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [39]:
tensor2 = torch.tensor([
    [[9., 10.], [11., 12,]],
    [[13., 14.], [15., 16.]]
])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [40]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [41]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [42]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [43]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


### 사칙연산: .add, .sub, .mul, .div

In [47]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [48]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [49]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [50]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

### 내적: .matmul

In [51]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])