In [2]:
import numpy as np

1. numpy의 기반 데이터 타입 : ndarray
2. array() : 다양한 타입(list etc.)의 인자를 입력받아 ndarray로 변환하는 기능
3. ndarray의 shape 변수 : ndarray의 크기(행, 열)를 튜플 형태로 가지고 있음 → ndarray의 차원까지 알 수 있음.

In [2]:
array1 = np.array([1, 2, 3])
print('array1 type: {0}'.format(type(array1)))
print('array1 array 형태: {0}'.format(array1.shape))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [3]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type: {0}'.format(type(array2)))
print('array2 array 형태: {0}'.format(array2.shape))

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [4]:
array3 = np.array([[1, 2, 3]])
print('array3 type: {0}'.format(type(array3)))
print('array3 array 형태: {0}'.format(array3.shape))

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


## ndarray의 데이터 타입

1. ndarray내의 데이터값은 숫자 값, 문자열 값, bool 값 모두 가능
2. 숫자형 - int형(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 32bit), float형(16bit, 32bit, 64bit, 128bit), complex type 제공
3. ndarray내의 데이터 타입은 같은 데이터 타입만 가능함
4. ndarray내의 데이터 타입은 dtype 속성으로 확인할 수 있음

In [6]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함

In [3]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [4]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


astype() : ndarray 내 데이터값의 타입변경, 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데, 메모리를 더 절약해야할 때 보통 이용함
ex) int형으로 충분한 경우인데, 데이터 타입이 float라면 int형으로 바꿔서 메모리를 절약할 수 있음

In [5]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [6]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [7]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우

arange() : array를 range()로 표현하는 것, 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해 줌

In [10]:
sequence_array = np.arange(1,10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[1 2 3 4 5 6 7 8 9]
int32 (9,)


zeros() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환함.
ones() : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환함.

함수 인자로 dtype을 지정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채움

In [11]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [12]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

reshape() : ndarray를 특정 차원 및 크기로 변환, 변환을 원하는 크기를 함수인자로 부여하면 됨.
지정된 사이즈로 변경이 불가능하면 오류가 발생함. ( (10, ) 데이터를 (4,3) 형태로 변경할 수 없음

In [14]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [16]:
array2 = array1.reshape(2,5)
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
array3 = array1.reshape(5,2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- reshape()의 인자로 -1을 사용하는 경우 : -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌

In [18]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
array2 = array1.reshape(-1, 5)
print("array2 shape:", array2.shape)

array2 shape: (2, 5)


In [20]:
array3 = array1.reshape(5, -1)
print("array3 shape:", array3.shape)

array3 shape: (5, 2)


In [21]:
array4 = array1.reshape(-1)
print("array4 shape:", array4.shape)

array4 shape: (10,)


-1 인자는 reshape(-1, 1)와 같은 형태로 자주 사용됨.
reshape(-1, 1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 row를 가지되 반드시 1개의 column을 가진 ndarray로 변환됨을 보장함.
여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용됨.

In [24]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [27]:
array5 = array3d.reshape(-1, 1)
print('array5d:\n', array5)
print('array5 shape:', array5.shape)

array5d:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
array5 shape: (8, 1)


In [28]:
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨
2. 슬라이싱 : 슬라이싱은 연속된 인덱스 상의 ndarray를 추출하는 방식. ex) 1:5, 시작 인덱스 1, 종료 인덱스 4까지에 해당하는 ndarray 반환
3. 팬시 인덱싱 (Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환함
4. 불린 인덱싱 (Boolean Indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환함

#### 1. 단일 값 추출

In [30]:
array1 = np.arange(1, 10)
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]


In [31]:
value = array1[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int32'>


In [33]:
# 뒤에서부터 데이터 추출하기
# index -1 : 맨 뒤의 데이터 값, index -2 : 맨 뒤에서 두 번째에 있는 데이터 값
print('맨 뒤의 값:', array1[-1], ' 맨 뒤에서 두 번째의 값:', array1[-2])

맨 뒤의 값: 9  맨 뒤에서 두 번째의 값: 8


In [34]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [35]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [36]:
'''
       ─────── axis1 : column방향
    │  ┌────┐
    │  │1│2│3 │
    │  │4│5│6 │
    │  │7│8│9 │
    │  └────┘
    axis0: row방향 
    
    2차원 배열 : axis 0, axis 1로 구분 (행, 열)
    3차원 배열 : axis 0, axis 1, axis 2로 구분 (행, 열, 높이)
'''

'\n       ─────── axis1 : column방향\n    │  ┌────┐\n    │  │1│2│3 │\n    │  │4│5│6 │\n    │  │7│8│9 │\n    │  └────┘\n    axis0: row방향 \n    \n    2차원 배열 : axis 0, axis 1로 구분 (행, 열)\n    3차원 배열 : axis 0, axis 1, axis 2로 구분 (행, 열, 높이)\n'

#### 2. 슬라이싱

슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입임.

In [38]:
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
2. ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [40]:
array1 = np.arange(1, 10)
array4 = array1[:3]
print(array4)

[1 2 3]


In [41]:
array5 = array1[3:]
print(array5)

[4 5 6 7 8 9]


In [45]:
array6 = array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]


2차원 ndarray에서의 슬라이싱도 1차원 ndarray에서의 슬라이싱과 유사, 단지 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다름

In [46]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('\narray2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('\narray2d[1:3, :]\n', array2d[1:3, :])
print('\narray2d[:, :]\n', array2d[:, :])
print('\narray2d[:2, 1:]\n', array2d[:2, 1:])
print('\narray2d[:2, 0]\n', array2d[:2, 0])

array2d[0:2, 0:2]
 [[1 2]
 [4 5]]

array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]

array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]

array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[:2, 1:]
 [[2 3]
 [5 6]]

array2d[:2, 0]
 [1 4]


In [49]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### 3. 팬시 인덱싱 (Fancy Indexing)
리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [51]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2] # (0,2), (1,2)
print('array2d[[0,1], 2]=> ', array3.tolist())

array2d[[0,1], 2]=>  [3, 6]


In [52]:
array4 = array2d[[0,1], 0:2] # ((0,0), (0,1)), ((1,0), (1,1))
print('array2d[[0,1], 0:2]=> ', array4.tolist())

array2d[[0,1], 0:2]=>  [[1, 2], [4, 5]]


In [53]:
array5 = array2d[[0, 1]] # ((0, :), (1, :))
print('array2d[[0, 1]]=> ', array5.tolist())

array2d[[0, 1]]=>  [[1, 2, 3], [4, 5, 6]]


#### 4. 불린 인덱싱 (Boolean Indexing)
조건 필터링과 검색을 동시에 할 수 있음

In [54]:
array1d = np.arange(1, 10)

# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print("array1d > 5 불린 인덱싱 결과 값:", array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [55]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [56]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print("불린 인덱스로 필터링 결과:", array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [57]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print("일반 인덱스로 필터링 결과: ", array4)

일반 인덱스로 필터링 결과:  [6 7 8 9]


## 행렬의 정렬 - sort()와 argsort()

#### 행렬 정렬
np.sort() : 넘파이에서 sort()를 호출하는 방식
ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식

np.sort()의 경우 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
ndarray.sort()는 원 행렬 자체를 정렬한 형태로 반환하며 반환값은 None임

In [2]:
import numpy as np

org_array = np.array([3,1,9,5])
print("원본 행렬:", org_array)

원본 행렬: [3 1 9 5]


In [4]:
sort_array1 = np.sort(org_array)
print("np.sort() 호출 후 반환된 정렬 행렬: ", sort_array1)
print("np.sort() 호출 후 원본 행렬: ", org_array)

np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]


In [5]:
sort_array2 = org_array.sort()
print("org_array.sort() 호출 후 반환된 행렬: ", sort_array2)
print("org_array.sort() 호출 후 원본 행렬: ", org_array)

org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [6]:
# 내림차순으로 정렬하기
sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순으로 정렬:", sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [8]:
#행렬이 2차원 이상일 경우, axis 축 값 설정을 통해 row방향 또는 column방향으로 정렬을 수행할 수 있음
array2d = np.array([[8, 12],
                    [7, 1]])

sort_array_2d_axis0 = np.sort(array2d, axis=0)
print("row 방향으로 정렬:\n", sort_array_2d_axis0)

sort_array_2d_axis1 = np.sort(array2d, axis=1)
print("\ncolumn 방향으로 정렬:\n", sort_array_2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]

column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기

np.argsort(): 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 이용, 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환함

In [9]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스:", sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [10]:
sort_indices_desc = np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:", sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [13]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print("성적 오름차순 정렬 시 score_array의 인덱스:", sort_indices_asc)
print("성적 오름차순으로 name_array의 이름 출력:", name_array[sort_indices_asc])

sort_indices_desc = np.argsort(score_array)[::-1]
print("성적 내림차순 정렬 시 score_array의 인덱스:", sort_indices_desc)
print("성적 내림차순으로 name_array의 이름 출력:", name_array[sort_indices_desc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
성적 내림차순 정렬 시 score_array의 인덱스: [3 1 4 2 0]
성적 내림차순으로 name_array의 이름 출력: ['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### 행렬 내적 (행렬 곱)
np.dot()을 사용해 계산

In [14]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print("행렬 내적 결과:\n", dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬

In [15]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)

print("A의 전치행렬:\n", transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]
